### API REGISTER
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{ 
"email": "rachaelcensuales@gmail.com",
"password": "1234"
}


### LOGIN 

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{ 
"username": "rachaelcensuales@gmail.com",
"password": "1234",
"deviceName": "deviceName"
    
}

### LOGOUT
GET http://localhost:3000/api/auth/logout
Content-Type: application/json
Authorization: 0.7350087161914725


### USERLIST
GET http://localhost:3000/api/users
Content-Type: application/json


### CREATE AD

POST http://localhost:3000/api/ads
Content-Type: application/json
Authorization:  8bd3c632aefd6

{ 
"title": "title",
"description": "description",
"category": "category",
"status": "status",
"price": 10,
"urlPhoto": "urlPhoto",
"address": "address",
"phone": 3331239456
}


### ADLIST

GET http://localhost:3000/api/ads
Content-Type: application/json


### UPDATE AD

PUT http://localhost:3000/api/ads/0.8289822723846443
Content-Type: application/json
Authorization: 0.1580580827003295

{

"title": "titolo",
"description": "description",
"category": "category",
"status": "status",
"price": 10,
"urlPhoto": "urlPhoto",
"address": "address",
"referenceKeyUser": 0.877869258874288,
"phone": 3331239456
}


###READ DEVICE 


# GET http://localhost:3000/api/devices
# Content-Type: application/json
# Authorization: 0.5462281196176055

### CREATE REPORT
POST http://localhost:3000/api/reports
Content-Type: application/json

{
"token": 0.5462281196176055,
"referenceKeyAd": 0.7770797288249514,
"description": "description",
"status": "status"
}

###DELETE AD 

DELETE http://localhost:3000/api/ads/0.42960124914251985
Content-Type: application/json 
Authorization: 0.4683058969076379


### READ PHONE NUMBER

GET http://localhost:3000/api/ads/0.3683984198356258
Content-Type: application/json
Authorization: 0.06457044822370683

# ### LEADSLIST

# GET http://localhost:3000/api/leads/0.3683984198356258
# Content-Type: application/json
# Authorization: 0.06457044822370683


### CREATE REVIEW
POST http://localhost:3000/api/63e7d341179eb/reviews
Content-Type: application/json
Authorization: 8bd3c632aefd6

{ 
"title": "title",
"description": "description",
"rating": "rating"
}

### DELETE REVIEW 

DELETE  http://localhost:3000/api/reviews/0.42960124914251985
Content-Type: application/json
Authorization: 

### DELETE ACCOUNT 

DELETE  http://localhost:3000/api/users/0.42960124914251985
Content-Type: application/json
Authorization: 

### UPDATE USERNAME 

PATCH http://localhost:3000/api/users/:primaryKeyUser
Content-Type: application/json
Authorization: 

{
    "username": "newusername"
}

###UPDATE AS SOLD 

PATCH http://localhost:3000/api/ads/:primaryKeyAd
Content-Type: application/json
Authorization: 

{ 
    "referenceKeyUserPurchased" : "djjdkd"
}

### FILTER AD 

POST http://localhost:3000/api/ads/
Content-Type: application/json
Authorization: 

{ 
    "price": 12,
    "category": "bitch",
    "status": "buono stato"
}

### CREATE FAVOURITE
POST http://localhost:3000/api/ads/:primaryKeyAd
Content-Type: application/json
Authorization: 


### DELETE FAVOURITE
DELETE http://localhost:3000/api/ads/:primaryKeyAd
Content-Type: application/json
Authorization: 

### GET FAVOURITE 

GET http://localhost:3000/api/favourites 
Content-Type: application/json
Authorization: 


### GET FILTERED AD BY TEXT

GET  http://localhost:3000/api/ads/:primaryKeyAd
Content-Type: application/json
Authorization: 